# This is a basic workflow to help you get started with Actions

name: covid

# Controls when the action will run. 
on:
  # schedule workflow
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
    # - cron: "0 0 * * *" #runs at 00:00 UTC everyday
    # - cron: "* * * * *" #runs at every minutes of every day
    - cron: "30 17 * * *" #runs at 19h30 every day
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #define environnemnt for pass variable
    environment: Token

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2 
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
          pip install tweepy<4.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a single command using the runners shell
      - name: Run Hello World!
        run: echo Hello, world!
        
      #- name: Download artefact file
      #  uses: actions/download-artifact@v2
      #  with:
      #    name: log

      # Runs a set of commands using the runners shell
      - name: Run script covid.py
        env:
          JU_TOKEN: "hello_ju"
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          echo Script in action... ${JU_TOKEN}
          python covid.py >> log.txt
          
      - name: Upload hello world file
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt
